### ISSUE TITLE
Patch Version bump for new module name

### ISSUE THREAD

**Issue by andrewhoff** [absmach/coap-cli#1]
Hey @dusanb94!

Just tried installing this CLI (it appears the binary release is not statically linked and as a result I'm getting an exec format error on darwin/amd64).

So I tried to go get this package, but it appears that a new version has not been tagged since the module name was fixed, so the latest tagged release actually has the incorrect module name.

Wondering if you'd be able to cut a new release for this?

**Comment by dborovcanin** [comment]
Hi @andrewhoff,

Release [v0.2.0](https://github.com/mainflux/coap-cli/releases/tag/v0.2.0) solves module import issue, and also adds darwin binary. Feel free to close this issue if everything works for you.

**Comment by dborovcanin** [comment]
Closed due to inactivity. @andrewhoff Feel free to reopen this issue if the release v0.2.0 does not solve your problems.
