### ISSUE TITLE
Undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall' and 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscallNoError'

### ISSUE THREAD

**Issue by advancedwebdeveloper** [absmach/coap-cli#3]
Hi.

I am experiencing such issues:

> $make
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:53: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:28: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:21: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscallNoError'
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:35: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:42: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscall'
> /home/oceanfish81/coap-cli/vendor/golang.org/x/sys/unix/gccgo.go:48: error: undefined reference to 'golang.x2eorg..z2fx..z2fsys..z2funix.realSyscallNoError'
> 

I am using

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64

with

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/coap-cli/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build992772685=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

CC @ianlancetaylor @thanm @cherrymui

**Comment by advancedwebdeveloper** [comment]
@ianlancetaylor , isn't this related to [https://github.com/golang/go/issues/41758](https://github.com/golang/go/issues/41758) ?

**Comment by drasko** [comment]
@advancedwebdeveloper please do not open issues here. It was mentioned many times that Mainflux does not have C bindings and is not using C at all.

**Comment by dborovcanin** [comment]
The problem seems to be related to LLVM or the Go compiler you are using (gollvm). This tool is written and compiled in the native Go compiler and you can find binaries for 3 platforms in the release assets (https://github.com/mainflux/coap-cli/releases/tag/v0.3.1).

**Comment by ianlancetaylor** [comment]
If `CGO_ENABLED` is set to `0` in the environment, then, yes, this is caused by golang/go#41758.

**Comment by dborovcanin** [comment]
Due to the reasons @drasko explained, `CGO_ENABLED` is disabled in this and all the other Mainflux tools.
